# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9393d731d58ac968a83cb2b1ca27806ec14f7c6d823f665f8fd7b5ad325ab8d05e81cbef841d3f7ec4c92ac02c3b977e458f905e7f2efb228934e324f2e7e50e

test:
  secret_key_base: 0aebcb6fe9d856ae0220f55e575ab9b26741c20a16cadcc8f32e7dd39287aa1a35dfaadea611cb4d0bfda9dc057df5130de54001f219fa4ec852f8702deefa8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
